Repository NVIDIA/cub, pull requests merged in 2020-11, with the labels that each got.

#210 Update DeviceScan to pass Thrust's scan tests
  cub/agent/agent_scan.cuh
  cub/device/dispatch/dispatch_scan.cuh
Labels: testing: dvs passed, testing: mc passed

#216 workarounds for clang-10 warnings
  cub/agent/agent_radix_sort_upsweep.cuh
  cub/agent/agent_reduce.cuh
  cub/block/block_load.cuh
  cub/block/block_radix_rank.cuh
  cub/block/block_store.cuh
  cub/block/specializations/block_reduce_raking.cuh
  cub/block/specializations/block_scan_raking.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/util_type.cuh
Labels: testing: dvs passed, testing: mc passed

#204 Faster Least Significant Digit Radix Sort Implementation
  .gitignore
  cub/agent/agent_radix_sort_downsweep.cuh
  cub/agent/agent_radix_sort_histogram.cuh
  cub/agent/agent_radix_sort_onesweep.cuh
  cub/block/block_radix_rank.cuh
  cub/block/radix_rank_sort_operations.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/util_ptx.cuh
Labels: blocked, testing: dvs passed, testing: mc passed

#225 Fix to support wrapping CUB in a custom outer namespace with macros
  cub/util_namespace.cuh
Labels: testing: dvs passed, testing: mc passed

#232 Correct the 1.10.0 changelog and start the 1.11.0 changelog
  CHANGELOG.md
Labels: docs

#231 Fix signedness mismatches in tests and don't warn about deprecated GPU architectures
  cmake/CubBuildCompilerTargets.cmake
  test/test_iterator.cu
  test/test_util.h
Labels: testing: dvs passed, testing: mc passed

#170 Fix CUDA version detection in CUB
  cub/util_arch.cuh
  cub/util_type.cuh
  test/test_device_radix_sort.cu
Labels: testing: dvs passed, testing: mc passed

#220 avoids clang -Wparentheses warning
  cub/util_device.cuh
Labels: testing: dvs passed, testing: mc passed

#233 Fix cub/util_type.cuh to not use 16-bit float with NVC++
  cub/util_type.cuh
  test/test_device_radix_sort.cu
Labels: testing: dvs passed, testing: mc passed

#217 Update install rules to install cmake into lib directory
  CMakeLists.txt
  cmake/CubCompilerHacks.cmake
  cmake/CubCudaConfig.cmake
  cmake/CubInstallRules.cmake
  cub/cmake/cub-config-version.cmake
  cub/cmake/cub-config.cmake
  test/CMakeLists.txt
  test/cmake/CMakeLists.txt
  test/cmake/test_install/CMakeLists.txt
Labels: cmake

#237 Fix radix sort perf regression.
  cub/device/dispatch/dispatch_radix_sort.cuh
Labels: P0, performance bug, testing: dvs passed

#240 Update with release info for 1.11.0.
  CHANGELOG.md
  README.md
Labels: docs
