Repository NVIDIA/cub, pull requests merged in 2021-08, with the labels that each got.

#351 Update histogram documentation.
  cub/device/device_histogram.cuh
Labels: only: docs

#352 cub::DeviceSpmv: Various fixes and tests
  cub/agent/agent_spmv_orig.cuh
  cub/device/device_spmv.cuh
  cub/device/dispatch/dispatch_spmv_orig.cuh
  cub/iterator/tex_obj_input_iterator.cuh
  test/test_device_spmv.cu
  test/test_util.h
Labels: testing: gpuCI passed, testing: internal ci passed

#348 Docs update: how to use dynamic shared mem with block reduce
  cub/block/block_discontinuity.cuh
  cub/block/block_exchange.cuh
  cub/block/block_histogram.cuh
  cub/block/block_load.cuh
  cub/block/block_merge_sort.cuh
  cub/block/block_radix_rank.cuh
  cub/block/block_radix_sort.cuh
  cub/block/block_reduce.cuh
  cub/block/block_scan.cuh
  cub/block/block_store.cuh
  examples/block/example_block_reduce.cu
  examples/block/example_block_reduce_dyn_smem.cu
Labels: only: docs, testing: gpuCI passed, P2: nice to have, only: tests

#358 Add 1.14.0 changelog.
  CHANGELOG.md
  README.md
Labels: only: docs, P0: must have
