Repository NVIDIA/cub, pull requests merged in 2021-05, with the labels that each got.

#303 [NVBug 3308316] Update deprecation messages for CTK 11.4.
  cub/util_cpp_dialect.cuh
Labels: P0: must have, nvbug

#309 Update CHANGELOG for 1.12.1.
  CHANGELOG.md
  README.md
Labels: only: docs

#290 Update device_segmented_reduce.cuh
  cub/device/device_segmented_reduce.cuh
Labels: only: docs, to close: integrate

#291 Allow segmented problems to have different types for offset iterators.
  cub/device/device_segmented_radix_sort.cuh
  cub/device/device_segmented_reduce.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/device/dispatch/dispatch_reduce.cuh
  test/test_device_radix_sort.cu
  test/test_device_reduce.cu
Labels: testing: internal ci passed, testing: mc passed

#298 Fix instructions on building cub
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: helps: pytorch, only: docs

#287 Fix cub::DeviceHistogram::MultiHistogramEven() 1-Dimensional overload, when OffsetT is not an `int`.
  cub/device/device_histogram.cuh
Labels: testing: internal ci passed, testing: mc passed

#301 Document that cub's device scan supports inplace operations, and add tests to enforce this feature.
  cub/device/device_scan.cuh
  test/test_device_scan.cu
Labels: helps: pytorch, only: gpuci, testing: mc passed
