Repository NVIDIA/cub, pull requests merged in 2021-12, with the labels that each got.

#410 Fix segmented sort device-side launch
  cub/device/dispatch/dispatch_segmented_sort.cuh
  test/test_device_segmented_sort.cu
Labels: testing: gpuCI passed, P0: must have, testing: internal ci passed

#411 Only use nv_exec_check_disable on nvcc.
  cub/detail/device_synchronize.cuh
  cub/detail/exec_check_disable.cuh
Labels: bug: functional, testing: gpuCI passed, nvbug, P0: must have, testing: internal ci passed

#331 Port adjacent difference into CUB
  cub/agent/agent_adjacent_difference.cuh
  cub/block/block_adjacent_difference.cuh
  cub/block/block_discontinuity.cuh
  cub/block/block_reduce.cuh
  cub/block/block_scan.cuh
  cub/cub.cuh
  cub/detail/type_traits.cuh
  cub/device/device_adjacent_difference.cuh
  cub/device/dispatch/dispatch_adjacent_difference.cuh
  cub/thread/thread_operators.cuh
  test/test_block_adjacent_difference.cu
  test/test_device_adjacent_difference.cu
Labels: enhancement, testing: gpuCI passed, P2: nice to have, testing: internal ci passed, release: breaking change

#404 Fix bad cast in util_device.
  cub/util_device.cuh
Labels: bug: functional, testing: gpuCI in progress, P0: must have, testing: internal ci in progress

#408 s/__NVCOMPILER_CUDA__/_NVHPC_CUDA/g
  cub/device/dispatch/dispatch_merge_sort.cuh
  cub/util_arch.cuh
  cub/util_compiler.cuh
  cub/util_debug.cuh
  cub/util_type.cuh
  test/test_device_radix_sort.cu
  test/test_device_segmented_sort.cu
Labels: enhancement, testing: gpuCI passed, compiler: nvc++, P1: should have, testing: internal ci in progress, helps: nvc++

#407 Add missing thrust headers after fixing header leak.
  test/test_device_merge_sort.cu
  test/test_device_segmented_sort.cu
  test/test_device_three_way_partition.cu
  test/test_thread_sort.cu
  test/test_warp_exchange.cu
Labels: bug: functional, testing: gpuCI in progress, P1: should have, testing: internal ci in progress, only: tests

#413 Enable CUB API deprecation warnings by default.
  CMakeLists.txt
Labels: bug: functional, testing: gpuCI in progress, P0: must have, testing: internal ci in progress

#403 Overhaul CUB test suite.
  CMakeLists.txt
  CONTRIBUTING.md
  cub/block/block_histogram.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/iterator/tex_ref_input_iterator.cuh
  test/CMakeLists.txt
  test/README.md
  test/test_block_histogram.cu
  test/test_block_load_store.cu
  test/test_block_radix_sort.cu
  test/test_block_radix_sort_160.cu
  test/test_block_radix_sort_32.cu
  test/test_block_radix_sort_64.cu
  test/test_block_reduce.cu
  test/test_block_scan.cu
  test/test_device_histogram.cu
  test/test_device_merge_sort.cu
  test/test_device_radix_sort.cu
  test/test_device_reduce.cu
  test/test_device_reduce_by_key.cu
  test/test_device_run_length_encode.cu
  test/test_device_scan.cu
  test/test_device_scan_by_key.cu
  test/test_device_select_if.cu
  test/test_device_select_unique.cu
  test/test_iterator.cu
  test/test_util.h
  test/test_warp_reduce.cu
  test/test_warp_scan.cu
Labels: testing: gpuCI in progress, P0: must have, testing: internal ci in progress, only: gpuci

#414 Skip pre-sorted tests for extended types.
  test/test_device_radix_sort.cu
Labels: testing: gpuCI in progress, P1: should have, only: gpuci, only: tests
