Repository NVIDIA/cub, pull requests merged in 2021-07, with the labels that each got.

#339 gpuCI fixes
  cmake/CubBuildCompilerTargets.cmake
  test/test_util.h
Labels: P0: must have, testing: gpuCI passed, testing: internal ci passed

#347 Use nvc++-friendly host/device switch pattern instead of CUB_PTX_ARCH.
  test/test_allocator.cu
  test/test_util.h
  test/test_warp_reduce.cu
Labels: testing: gpuCI in progress, testing: internal ci passed

#328 Small fixes for CachingDeviceAllocator
  cub/util_allocator.cuh
Labels: testing: gpuCI in progress, testing: internal ci in progress

#335 Fix clang compile error
  cub/block/radix_rank_sort_operations.cuh
Labels: testing: gpuCI in progress, testing: internal ci in progress

#325 Avoid warnings about unreachable code
  cub/block/radix_rank_sort_operations.cuh
Labels: compiler: nvc++, helps: nvc++, testing: gpuCI in progress, testing: internal ci in progress

#350 Notify users that CUB_NS_QUALIFIER must be set when using other NS macros
  cub/util_namespace.cuh
Labels: testing: gpuCI passed, testing: internal ci passed

#163 Fixes Issues #161 and #162
  cub/device/dispatch/dispatch_spmv_orig.cuh
  cub/iterator/tex_obj_input_iterator.cuh
  cub/iterator/tex_ref_input_iterator.cuh
  experimental/spmv_compare.cu
Labels: bug: functional, testing: gpuCI passed, testing: internal ci passed
