Repository NVIDIA/cub, pull requests merged in 2021-11, with the labels that each got.

#397 Add check for nvhpc stdpar numeric header.
  test/cmake/check_source_files.cmake
Labels: enhancement, P1: should have, only: gpuci, helps: nvc++

#402 Increase floating point tolerance when validating results.
  test/test_util.h
Labels: testing: gpuCI in progress, compiler: nvc++, P1: should have, only: gpuci, only: tests, helps: nvc++

#346 Permutation-based tests for sorting
  cub/util_type.cuh
  test/bfloat16.h
  test/half.h
  test/test_device_radix_sort.cu
  test/test_util.h
Labels: enhancement, testing: gpuCI in progress, P2: nice to have, testing: internal ci in progress
