Repository NVIDIA/cub, pull requests merged in 2021-06, with the labels that each got.

#307 Radix sort stability docs
  cub/block/block_radix_sort.cuh
  cub/device/device_radix_sort.cuh
  cub/device/device_segmented_radix_sort.cuh
Labels: only: docs

#306 Add BFloat16 support for radix sort
  cub/device/device_radix_sort.cuh
  cub/util_type.cuh
  test/bfloat16.h
  test/test_device_radix_sort.cu
  test/test_util.h
Labels: testing: internal ci passed, testing: mc passed

#311 Fix block shuffle
  cmake/CubCudaConfig.cmake
  cub/block/block_shuffle.cuh
  test/test_block_shuffle.cu
Labels: testing: internal ci passed, testing: mc passed

#316 Remove WARP_TIME_SLICING template param desc.
  cub/block/block_store.cuh
Labels: only: docs

#274 Add BLOCK_LOAD_STRIPED and BLOCK_STORE_STRIPED
  cub/block/block_load.cuh
  cub/block/block_store.cuh
  test/test_block_load_store.cu
Labels: P1: should have, enhancement, testing: internal ci passed, testing: mc passed

#320 Deprecate TexRefInputIterator.
  CMakeLists.txt
  cub/agent/agent_spmv_orig.cuh
  cub/cmake/cub-config.cmake
  cub/iterator/tex_obj_input_iterator.cuh
  cub/iterator/tex_ref_input_iterator.cuh
  cub/util_deprecated.cuh
  test/test_iterator.cu
Labels: testing: gpuCI passed, testing: internal ci passed

#321 Subdomains of github.com are deprecated for GitHub Pages
  README.md
Labels: only: docs

#319 Fix OOB access in FlagHeadsAndTails
  cub/block/block_discontinuity.cuh
Labels: testing: gpuCI passed, testing: internal ci passed

#277 Fixed sanitizer warnings in RadixSortScanBinsKernel
  cub/device/dispatch/dispatch_radix_sort.cuh
Labels: P1: should have, bug: functional, testing: gpuCI in progress, testing: internal ci in progress

#323 Update changelog and readme for the 1.13.0 release.
  CHANGELOG.md
  README.md
Labels: only: docs

#330 Update 1.13.0 Changelog with summary.
  CHANGELOG.md
Labels: only: docs
