Repository NVIDIA/cub, pull requests merged in 2022-05, with the labels that each got.

#469 WAR nvc++ bug:
  cub/thread/thread_operators.cuh
Labels: testing: gpuCI in progress, compiler: nvc++, P1: should have, type: bug: compiler

#466 Alternative approach to 64-bit indexing in adjacent difference
  cub/detail/choose_offset.cuh
  cub/device/device_adjacent_difference.cuh
  cub/device/device_radix_sort.cuh
  test/test_device_adjacent_difference.cu
Labels: type: bug: functional, testing: gpuCI passed, P1: should have

#465 Remove unused/obsolete files.
  common.mk
  experimental/.gitignore
  experimental/defunct/example_coo_spmv.cu
  experimental/defunct/test_device_seg_reduce.cu
  experimental/histogram/histogram_cub.h
  experimental/histogram/histogram_gmem_atomics.h
  experimental/histogram/histogram_smem_atomics.h
  experimental/histogram_compare.cu
  experimental/sparse_matrix.h
  experimental/spmv_compare.cu
  experimental/spmv_script.sh
  tune/.gitignore
  tune/tune_device_reduce.cu
Labels: testing: gpuCI passed, P2: nice to have

#470 fix doxygen warnings
  cub/block/block_adjacent_difference.cuh
  cub/block/block_shuffle.cuh
  cub/device/device_partition.cuh
  cub/device/device_scan.cuh
  cub/util_device.cuh
  cub/version.cuh
  cub/warp/warp_load.cuh
Labels: only: docs, type: bug: functional, P1: should have, area: docs

#474 Update changelog for 1.17.0.
  CHANGELOG.md
  README.md
Labels: only: docs

#483 Allow device lambdas in device adjacent difference
  cub/device/dispatch/dispatch_adjacent_difference.cuh
Labels: testing: gpuCI passed, P0: must have

#476 debug_synchronous support in Onesweep sort
  cub/device/dispatch/dispatch_radix_sort.cuh
Labels: type: bug: functional, testing: gpuCI passed, P1: should have

#488 Wrap `AgentScanByKey::TempStorage` in `cub::Uninitialized`.
  cub/agent/agent_scan_by_key.cuh
Labels: type: bug: functional, compiler: nvc++, P0: must have, type: bug: compiler, release: backport

#490 In-place guarantees for scan algorithms
  cub/agent/agent_scan_by_key.cuh
  cub/device/device_scan.cuh
  cub/device/dispatch/dispatch_scan.cuh
  cub/device/dispatch/dispatch_scan_by_key.cuh
  test/test_device_scan.cu
  test/test_device_scan_by_key.cu
Labels: testing: gpuCI passed

#492 Fix in-place execution of adjacent difference
  cub/device/dispatch/dispatch_adjacent_difference.cuh
Labels: type: bug: functional, testing: gpuCI passed, P0: must have
