Repository NVIDIA/cub, pull requests merged in 2022-12, with the labels that each got.

#365 Draft for catch2 testing framework usage
  .gitignore
  CMakeLists.txt
  cmake/CPM.cmake
  cmake/CubBuildCompilerTargets.cmake
  docs/test_overview.md
  test/CMakeLists.txt
  test/c2h/custom_type.cuh
  test/c2h/generators.cu
  test/c2h/generators.cuh
  test/catch2_runner.cu
  test/catch2_test_block_adjacent_difference.cu
  test/catch2_test_block_histogram.cu
  test/catch2_test_block_load.cu
  test/catch2_test_block_merge_sort.cu
  test/catch2_test_block_radix_sort.cu
  test/catch2_test_block_reduce.cu
  test/catch2_test_block_run_length_decode.cu
  test/catch2_test_block_scan.cu
  test/catch2_test_block_shuffle.cu
  test/catch2_test_block_store.cu
  test/catch2_test_helper.h
  test/test_block_adjacent_difference.cu
  test/test_block_histogram.cu
  test/test_block_load_store.cu
  test/test_block_merge_sort.cu
  test/test_block_radix_sort.cu
  test/test_block_reduce.cu
  test/test_block_scan.cu
  test/test_block_shuffle.cu
  test/test_util.h
  test/test_util_vec.h
Labels: testing: gpuCI passed, P2: nice to have

#601 Ctk12 sync
  README.md
  cmake/CubCudaConfig.cmake
  cub/detail/detect_cuda_runtime.cuh
  cub/detail/device_synchronize.cuh
  cub/util_device.cuh
Labels: testing: gpuCI in progress, P0: must have

#359 Adds DeviceBatchMemcpy algorithm and tests
  .clang-format
  cub/agent/agent_batch_memcpy.cuh
  cub/agent/single_pass_scan_operators.cuh
  cub/cub.cuh
  cub/device/device_memcpy.cuh
  cub/device/dispatch/dispatch_batch_memcpy.cuh
  test/test_device_batch_memcpy.cu
  test/test_device_merge_sort.cu
Labels: testing: gpuCI passed, helps: rapids
