Repository NVIDIA/cub, pull requests merged in 2022-11, with the labels that each got.

#588 Fix warp scan test
  test/test_warp_scan.cu
Labels: type: bug: functional, testing: gpuCI in progress, P0: must have

#586 Add option to opt out CDP
  .clangd
  cub/detail/detect_cuda_runtime.cuh
Labels: testing: gpuCI in progress, P0: must have

#585 Sorting policy for H100
  cub/device/dispatch/dispatch_radix_sort.cuh
Labels: testing: gpuCI passed, P1: should have

#590 Correct install(DIRECTORY ... PATTERN) which matches at end of file name
  cmake/CubInstallRules.cmake
Labels: type: bug: functional, area: cmake

#589 Support reduction for more than 2^31 items
  cub/device/device_reduce.cuh
  test/test_device_reduce.cu
Labels: type: bug: functional, P1: should have

#595 Fix seg sort for bool keys
  cub/agent/agent_sub_warp_merge_sort.cuh
  test/test_device_segmented_sort.cu
Labels: P0: must have

#592 Fix overflow in reduce
  cub/agent/agent_reduce.cuh
  test/test_device_reduce.cu
Labels: type: bug: functional, P0: must have

#598 Fix RLE when items[0] is NaN
  cub/agent/agent_reduce_by_key.cuh
  test/test_device_run_length_encode.cu
Labels: type: bug: functional, testing: gpuCI passed, P1: should have
