Repository NVIDIA/cub, pull requests merged in 2022-02, with the labels that each got.

#393 Fix some min/max macro collisions with windows.h
  cmake/header_test.in
  test/bfloat16.h
  test/half.h
  test/test_device_segmented_sort.cu
Labels: P2: nice to have, only: tests

#381 Fix alignment in dyn_smem example
  examples/block/example_block_reduce_dyn_smem.cu
Labels: bug: functional, testing: gpuCI in progress, P1: should have, only: gpuci

#392 Update header tests to check for termios.h's B0 macro.
  cmake/header_test.in
Labels: enhancement, only: cmake, testing: gpuCI in progress, only: gpuci, only: tests

#430 Remove references to alpha/beta from DeviceSpmv docs.
  cub/device/device_spmv.cuh
Labels: only: docs

#431 Update incorrect comments in test_block_radix_sort.
  test/test_block_radix_sort.cu
Labels: only: docs

#433 Update CHANGELOG.md and README.md for 1.16.0.
  CHANGELOG.md
  README.md
Labels: only: docs

#437 Add missing <iterator> headers.
  cub/device/dispatch/dispatch_adjacent_difference.cuh
  cub/device/dispatch/dispatch_unique_by_key.cuh
  cub/util_type.cuh
Labels: bug: functional, testing: gpuCI in progress, P0: must have, helps: quda
