Repository NVIDIA/cub, pull requests merged in 2022-09, with the labels that each got.

#564 Fix block radix rank for blocks with non multiple of 32 threads
  cub/agent/agent_radix_sort_downsweep.cuh
  cub/block/block_radix_rank.cuh
  cub/util_ptx.cuh
  test/test_block_radix_rank.cu
Labels: type: bug: functional, testing: gpuCI in progress

#568 Add initial version of clang-tidy
  .clang-tidy
Labels: P2: nice to have

#547 Fix of CUB linkage
  cub/util_namespace.cuh
Labels: testing: gpuCI passed

#571 Don't use char in tests
  test/test_block_load_store.cu
  test/test_block_radix_sort.cu
  test/test_block_reduce.cu
  test/test_device_radix_sort.cu
  test/test_device_reduce.cu
  test/test_device_reduce_by_key.cu
  test/test_device_run_length_encode.cu
  test/test_device_scan.cu
  test/test_device_scan_by_key.cu
  test/test_device_spmv.cu
  test/test_iterator.cu
  test/test_iterator_deprecated.cu
  test/test_util.h
  test/test_warp_reduce.cu
Labels: type: enhancement, testing: gpuCI passed, only: tests, area: tests

#572 Use inline namespace
  cub/util_namespace.cuh
Labels: testing: gpuCI passed

#574 Backport CUB linkage fix into 2.0
  cub/util_namespace.cuh
Labels: testing: gpuCI in progress
