Repository NVIDIA/cub, pull requests merged in 2022-04, with the labels that each got.

#451 Alias deprecated TexRefInputIterator to TexObjInputIterator.
  cmake/CubBuildCompilerTargets.cmake
  cub/iterator/tex_obj_input_iterator.cuh
  cub/iterator/tex_ref_input_iterator.cuh
  test/test_iterator.cu
  test/test_iterator_deprecated.cu
Labels: testing: gpuCI in progress, P0: must have, only: gpuci

#455 Fix CDP build for radix sort test
  test/test_device_radix_sort.cu
Labels: bug: functional, testing: gpuCI in progress, P1: should have

#462 Fix segmented sort for SM{61,70}
  cub/device/dispatch/dispatch_segmented_sort.cuh
Labels: bug: functional, testing: gpuCI passed, P0: must have

#450 update Iterate (BlockDiscontinuity) to use pragma unroll
  cub/block/block_discontinuity.cuh
Labels: enhancement, testing: gpuCI in progress, P1: should have

#456 pragma unroll in block_adjacent_difference::Iterate
  cub/block/block_adjacent_difference.cuh
Labels: enhancement, testing: gpuCI in progress, P2: nice to have

#464 Normalize flags in select flagged
  cub/agent/agent_select_if.cuh
  cub/device/dispatch/dispatch_three_way_partition.cuh
  cub/device/dispatch/dispatch_unique_by_key.cuh
  test/test_device_select_if.cu
Labels: bug: functional, testing: gpuCI in progress, P1: should have
