Repository NVIDIA/cub, pull requests merged in 2022-07, with the labels that each got.

#524 Fix device-side debug synchronous usage for seg sort
  cub/device/dispatch/dispatch_segmented_sort.cuh
Labels: type: bug: functional, testing: gpuCI in progress

#528 Disable managed memory for nvc++
  cmake/CubBuildCompilerTargets.cmake
Labels: testing: gpuCI passed

#527 Deprecate debug synchronous
  cub/device/device_adjacent_difference.cuh
  cub/device/device_histogram.cuh
  cub/device/device_merge_sort.cuh
  cub/device/device_partition.cuh
  cub/device/device_radix_sort.cuh
  cub/device/device_reduce.cuh
  cub/device/device_run_length_encode.cuh
  cub/device/device_scan.cuh
  cub/device/device_segmented_radix_sort.cuh
  cub/device/device_segmented_reduce.cuh
  cub/device/device_segmented_sort.cuh
  cub/device/device_select.cuh
  cub/device/device_spmv.cuh
  cub/device/dispatch/dispatch_adjacent_difference.cuh
  cub/device/dispatch/dispatch_histogram.cuh
  cub/device/dispatch/dispatch_merge_sort.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/device/dispatch/dispatch_reduce.cuh
  cub/device/dispatch/dispatch_reduce_by_key.cuh
  cub/device/dispatch/dispatch_rle.cuh
  cub/device/dispatch/dispatch_scan.cuh
  cub/device/dispatch/dispatch_scan_by_key.cuh
  cub/device/dispatch/dispatch_segmented_sort.cuh
  cub/device/dispatch/dispatch_select_if.cuh
  cub/device/dispatch/dispatch_spmv_orig.cuh
  cub/device/dispatch/dispatch_three_way_partition.cuh
  cub/device/dispatch/dispatch_unique_by_key.cuh
  cub/util_debug.cuh
  cub/util_deprecated.cuh
  cub/util_device.cuh
  test/CMakeLists.txt
  test/test_device_adjacent_difference.cu
  test/test_device_histogram.cu
  test/test_device_merge_sort.cu
  test/test_device_radix_sort.cu
  test/test_device_reduce.cu
  test/test_device_reduce_by_key.cu
  test/test_device_run_length_encode.cu
  test/test_device_scan.cu
  test/test_device_scan_by_key.cu
  test/test_device_segmented_sort.cu
  test/test_device_select_if.cu
  test/test_device_select_unique.cu
  test/test_device_select_unique_by_key.cu
  test/test_device_spmv.cu
  test/test_device_three_way_partition.cu
Labels: testing: gpuCI passed, P0: must have

#533 Fix cub::Debug for builds without RDC
  cub/util_debug.cuh
Labels: testing: gpuCI passed, P1: should have

#518 Fix warp merge sort docs
  cub/warp/warp_merge_sort.cuh
Labels: only: docs

#516 Fix main/GitHub/warp reduce
  cub/warp/specializations/warp_reduce_shfl.cuh
  cub/warp/warp_reduce.cuh
  test/test_warp_reduce.cu
Labels: testing: gpuCI passed

#529 Backport adjacent difference fixes
  cub/agent/agent_adjacent_difference.cuh
  cub/block/block_adjacent_difference.cuh
  cub/device/dispatch/dispatch_adjacent_difference.cuh
  test/test_block_adjacent_difference.cu
  test/test_device_adjacent_difference.cu
Labels: testing: internal ci passed

#535 Improve nvhpc configuration
  cmake/CubBuildCompilerTargets.cmake
  cmake/CubCompilerHacks.cmake
Labels: P2: nice to have

#534 Remove usage of find_path to locate cub/version.cuh
  cub/cmake/cub-header-search.cmake
Labels: only: cmake, type: bug: functional, testing: gpuCI in progress, P1: should have, helps: rapids, area: cmake
