Repository NVIDIA/cub, pull requests merged in 2022-08, with the labels that each got.

#509 P2322R6 accumulator types for reduce
  cub/agent/agent_reduce.cuh
  cub/block/specializations/block_reduce_warp_reductions.cuh
  cub/detail/type_traits.cuh
  cub/device/device_reduce.cuh
  cub/device/dispatch/dispatch_reduce.cuh
  cub/thread/thread_operators.cuh
  cub/thread/thread_reduce.cuh
  test/test_block_reduce.cu
  test/test_block_scan.cu
  test/test_device_reduce.cu
  test/test_device_reduce_by_key.cu
  test/test_device_scan.cu
  test/test_device_scan_by_key.cu
  test/test_thread_operators.cu
  test/test_warp_reduce.cu
  test/test_warp_scan.cu
Labels: type: bug: functional, testing: gpuCI passed, P1: should have, release: breaking change

#511 P2322R6 accumulator types for scan and reduce by key
  cub/agent/agent_reduce_by_key.cuh
  cub/agent/agent_scan.cuh
  cub/agent/agent_scan_by_key.cuh
  cub/agent/single_pass_scan_operators.cuh
  cub/block/block_exchange.cuh
  cub/block/specializations/block_reduce_warp_reductions.cuh
  cub/block/specializations/block_scan_warp_scans.cuh
  cub/detail/uninitialized_copy.cuh
  cub/device/device_scan.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/device/dispatch/dispatch_reduce.cuh
  cub/device/dispatch/dispatch_reduce_by_key.cuh
  cub/device/dispatch/dispatch_scan.cuh
  cub/device/dispatch/dispatch_scan_by_key.cuh
  cub/thread/thread_store.cuh
  cub/util_type.cuh
  test/test_device_reduce_by_key.cu
  test/test_device_scan.cu
  test/test_device_scan_by_key.cu
Labels: type: enhancement, testing: gpuCI passed, P1: should have, release: breaking change

#542 Add option to build with C++20.
  cmake/CubBuildTargetList.cmake
Labels: type: enhancement, only: cmake, testing: gpuCI in progress, P0: must have, area: cmake

#538 Temporarily disable tests for non-RDC architectures.
  cmake/CubCudaConfig.cmake
  examples/CMakeLists.txt
  test/CMakeLists.txt
Labels: only: cmake, type: bug: functional, testing: gpuCI passed, P0: must have, area: ci, area: cmake

#543 Remove minimal supported version for NVC++
  README.md
Labels: only: docs

#481 Fix begin_bit == end_bit == 0 for device-wide and segmented sort
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/util_device.cuh
  test/test_device_radix_sort.cu
Labels: type: bug: functional, testing: gpuCI passed, P2: nice to have

#487 Fix DeviceHistogram::Even for mixed float/int levels and sample types.
  cub/detail/cpp_compatibility.cuh
  cub/device/device_histogram.cuh
  cub/device/dispatch/dispatch_histogram.cuh
  test/test_device_histogram.cu
Labels: type: bug: functional, testing: gpuCI in progress, P1: should have, release: breaking change

#549 Fix BlockReduceRaking non-commutative docs
  cub/block/specializations/block_reduce_raking.cuh
Labels: only: docs, area: docs

#554 Fix uninitialized copy for NVHPC
  cub/detail/uninitialized_copy.cuh
Labels: compiler: nvc++, P0: must have, type: bug: compiler

#553 Deprecate CTK<9
  cub/util_arch.cuh
  cub/util_ptx.cuh
  cub/warp/specializations/warp_reduce_shfl.cuh
  cub/warp/specializations/warp_scan_shfl.cuh
Labels: testing: gpuCI in progress, P2: nice to have, release: breaking change

#555 Fix VS22 build
  test/test_block_merge_sort.cu
Labels: P1: should have, type: bug: compiler, compiler: msvc

#537 First version of developer overview
  docs/developer_overview.md
Labels: only: docs, area: docs

#558 Add clang-format
  .clang-format
Labels: only: docs, area: docs

#562 Fix wrong tid when blockDim.y or z > 1
  cub/block/block_shuffle.cuh
  test/test_block_shuffle.cu
Labels: type: bug: functional, testing: gpuCI in progress, P0: must have
