Repository NVIDIA/cub, pull requests merged in 2022-06, with the labels that each got.

#498 Add missing colon in cub::BlockAdjacentDifference::FlagTails
  cub/block/block_adjacent_difference.cuh
Labels: type: bug: functional, P0: must have, release: backport

#495 In-place guarantees for partition
  cub/device/device_partition.cuh
  test/test_device_select_if.cu
Labels: type: enhancement, testing: gpuCI passed, P1: should have, area: docs

#501 In-place guarantees for rle
  cub/device/device_run_length_encode.cuh
Labels: type: enhancement, only: docs, P1: should have, area: docs

#480 Add option to disable BF16 support
  cmake/CubHeaderTesting.cmake
  cmake/header_test.in
  cub/util_type.cuh
Labels: type: enhancement, testing: gpuCI passed, P1: should have

#503 In place select
  cub/device/device_select.cuh
  cub/device/dispatch/dispatch_select_if.cuh
  test/test_device_select_if.cu
Labels: type: enhancement, testing: gpuCI passed, P1: should have, area: docs, area: tests

#508 Fix temp storage allocation in adjacent difference copy
  cub/agent/agent_adjacent_difference.cuh
  cub/block/block_adjacent_difference.cuh
  cub/device/dispatch/dispatch_adjacent_difference.cuh
  test/test_block_adjacent_difference.cu
  test/test_device_adjacent_difference.cu
Labels: type: bug: functional, testing: gpuCI passed, P0: must have

#500 In-place guarantees for reduce
  cub/device/device_reduce.cuh
  cub/device/device_segmented_reduce.cuh
Labels: type: enhancement, only: docs, P1: should have, area: docs

#499 In-place guarantees for sort
  cub/device/device_radix_sort.cuh
  cub/device/device_segmented_radix_sort.cuh
  cub/device/device_segmented_sort.cuh
Labels: type: enhancement, only: docs, P1: should have, area: docs

#514 Support __half in histogram
  cub/device/dispatch/dispatch_histogram.cuh
  cub/thread/thread_search.cuh
  test/half.h
  test/test_device_histogram.cu
Labels: type: enhancement, P1: should have

#520 Remove block scan research leftovers
  cub/block/specializations/block_scan_warp_scans2.cuh
  cub/block/specializations/block_scan_warp_scans3.cuh
Labels: type: cleanup

#513 Reapply changes from NVIDIA/cub#404 that were lost in conflict resolution.
  cub/util_device.cuh
Labels: type: bug: functional, testing: gpuCI passed, P0: must have
