Repository NVIDIA/cub, pull requests merged in 2022-01, with the labels that each got.

#415 Support user defined CMAKE_INSTALL_INCLUDEDIR values
  cmake/CubInstallRules.cmake
  cub/cmake/cub-config-version.cmake
  cub/cmake/cub-header-search.cmake
  cub/cmake/cub-header-search.cmake.in
Labels: enhancement, only: cmake, P1: should have, helps: rapids

#418 Tell gcc this sizeof division is intended ( -Wsizeof-array-div )
  cub/util_type.cuh
Labels: bug: functional, testing: gpuCI in progress, P1: should have, testing: internal ci in progress

#420 Initialize padding member to silence warning.
  cub/iterator/discard_output_iterator.cuh
Labels: bug: functional, testing: gpuCI in progress, P1: should have, testing: internal ci in progress

#421 Fix spurious uninitialized variable warning on gcc11.
  test/half.h
Labels: bug: functional, testing: gpuCI in progress, P1: should have, testing: internal ci in progress

#423 Fix segmented sort compilation in case of windows.h
  cmake/header_test.in
  cub/device/dispatch/dispatch_segmented_sort.cuh
Labels: testing: gpuCI in progress, P1: should have, testing: internal ci in progress

#424 Fix segfault in device radix sort tests
  test/test_device_radix_sort.cu
Labels: bug: functional, testing: gpuCI in progress, P1: should have, only: gpuci, only: tests

#426 Fix version checks in CMake packages.
  cub/cmake/cub-config-version.cmake
Labels: only: cmake, bug: functional, testing: gpuCI in progress, P0: must have, only: gpuci, helps: rapids

#340 64-bit Offsets in DeviceRadixSort
  cub/agent/agent_radix_sort_histogram.cuh
  cub/agent/agent_radix_sort_onesweep.cuh
  cub/device/device_radix_sort.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  test/test_device_radix_sort.cu
Labels: enhancement, testing: gpuCI in progress, P1: should have, testing: internal ci in progress
