Repository NVIDIA/cub, pull requests merged in 2023-01, with the labels that each got.

#607 Support __{u,}int128_t in radix sort
  cub/util_ptx.cuh
  cub/util_type.cuh
  test/catch2_test_printing.cu
  test/test_block_radix_rank.cu
  test/test_device_batch_memcpy.cu
  test/test_device_radix_sort.cu
  test/test_util.h
Labels: testing: gpuCI passed, P2: nice to have

#609 Use libcu++ function objects
  cub/thread/thread_operators.cuh
  cub/util_device.cuh
  cub/util_macro.cuh
Labels: testing: gpuCI passed, P2: nice to have

#611 Fix warp scan exlusive sum for vector types
  cub/warp/warp_scan.cuh
  test/test_warp_scan.cu
Labels: type: bug: functional, testing: gpuCI in progress, release: breaking change

#617 Fix Clang CUDA
  cmake/CubCudaConfig.cmake
  cmake/CubUtilities.cmake
  cub/device/dispatch/dispatch_batch_memcpy.cuh
  cub/warp/specializations/warp_reduce_shfl.cuh
  test/CMakeLists.txt
  test/c2h/custom_type.cuh
  test/c2h/generators.cuh
  test/catch2_test_printing.cu
Labels: testing: gpuCI in progress

#618 Test reduction with bf16 and fp16
  test/test_device_reduce.cu
Labels: testing: gpuCI passed
