Repository NVIDIA/cub, pull requests merged in 2023-04, with the labels that each got.

#660 Migrates remaining warp-scope tests to Catch2
  test/c2h/custom_type.cuh
  test/catch2_test_warp_load.cu
  test/catch2_test_warp_merge_sort.cu
  test/catch2_test_warp_reduce.cu
  test/test_warp_load.cu
  test/test_warp_merge_sort.cu
  test/test_warp_reduce.cu
Labels: testing: gpuCI passed

#681 Backport fixes for reordering in CUB member initializer lists into 2.0 branch
  cmake/CubBuildCompilerTargets.cmake
  cub/agent/agent_histogram.cuh
  cub/agent/agent_select_if.cuh
  cub/block/block_exchange.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
Labels: testing: gpuCI in progress

#683 Limits tests for generic WarpReduce tests to builtin types
  test/catch2_test_warp_reduce.cu
Labels: cub

#684 Removes unused variables in DeviceCopy::Batched
  test/test_device_batch_copy.cu
Labels: only: tests, area: tests
