Repository NVIDIA/cub, pull requests merged in 2023-05, with the labels that each got.

#687 Fixes narrowing conversion warning in tests
  test/test_device_batch_copy.cu
Labels: only: tests, area: tests

#688 CUB Tuning Infrastructure
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  benchmarks/README.md
  benchmarks/bench/merge_sort/keys.cu
  benchmarks/bench/merge_sort/pairs.cu
  benchmarks/bench/partition/flagged.cu
  benchmarks/bench/partition/if.cu
  benchmarks/bench/radix_sort/keys.cu
  benchmarks/bench/radix_sort/pairs.cu
  benchmarks/bench/reduce/base.cuh
  benchmarks/bench/reduce/max.cu
  benchmarks/bench/reduce/sum.cu
  benchmarks/bench/scan/exclusive/base.cuh
  benchmarks/bench/scan/exclusive/by_key.cu
  benchmarks/bench/scan/exclusive/max.cu
  benchmarks/bench/scan/exclusive/sum.cu
  benchmarks/bench/select/flagged.cu
  benchmarks/bench/select/if.cu
  benchmarks/docker/.gitignore
  benchmarks/docker/recipe.py
  benchmarks/nvbench_helper/CMakeLists.txt
  benchmarks/nvbench_helper/nvbench_helper.cu
  benchmarks/nvbench_helper/nvbench_helper.cuh
  benchmarks/scripts/.gitignore
  benchmarks/scripts/analysis.ipynb
  benchmarks/scripts/analyze.py
  benchmarks/scripts/cub/__init__.py
  benchmarks/scripts/cub/bench/__init__.py
  benchmarks/scripts/cub/bench/bench.py
  benchmarks/scripts/cub/bench/build.py
  benchmarks/scripts/cub/bench/cmake.py
  benchmarks/scripts/cub/bench/config.py
  benchmarks/scripts/cub/bench/logger.py
  benchmarks/scripts/cub/bench/score.py
  benchmarks/scripts/cub/bench/search.py
  benchmarks/scripts/cub/bench/storage.py
  benchmarks/scripts/search.py
  benchmarks/scripts/verify.py
  cub/agent/single_pass_scan_operators.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/device/dispatch/dispatch_select_if.cuh
  docs/tuning.rst
Labels: testing: gpuCI passed

#671 Support user-defined types in radix sort and introduce initial sphinx docs
  .clangd
  README.md
  cub/agent/agent_radix_sort_downsweep.cuh
  cub/agent/agent_radix_sort_histogram.cuh
  cub/agent/agent_radix_sort_onesweep.cuh
  cub/agent/agent_radix_sort_upsweep.cuh
  cub/agent/agent_segmented_radix_sort.cuh
  cub/agent/agent_sub_warp_merge_sort.cuh
  cub/block/block_radix_rank.cuh
  cub/block/block_radix_sort.cuh
  cub/block/radix_rank_sort_operations.cuh
  cub/device/device_radix_sort.cuh
  cub/device/device_reduce.cuh
  cub/device/dispatch/dispatch_radix_sort.cuh
  cub/util_ptx.cuh
  cub/util_type.cuh
  docs/.gitignore
  docs/VERSION.md
  docs/deps/repo-deps.packman.xml
  docs/developer_overview.md
  docs/developer_overview.rst
  docs/gen_docs.sh
  docs/index.rst
  docs/repo.bat
  docs/repo.sh
  docs/repo.toml
  docs/test_overview.md
  docs/test_overview.rst
  docs/tools/packman/bootstrap/configure.bat
  docs/tools/packman/bootstrap/download_file_from_url.ps1
  docs/tools/packman/bootstrap/fetch_file_from_packman_bootstrap.cmd
  docs/tools/packman/bootstrap/generate_temp_file_name.ps1
  docs/tools/packman/bootstrap/generate_temp_folder.ps1
  docs/tools/packman/bootstrap/install_package.py
  docs/tools/packman/config.packman.xml
  docs/tools/packman/packman
  docs/tools/packman/packman.cmd
  docs/tools/packman/packmanconf.py
  docs/tools/packman/python.bat
  docs/tools/packman/python.sh
  docs/tools/repoman/omni/repo/format/.gitignore
  docs/tools/repoman/repoman.py
  examples/device/example_device_radix_sort_custom.cu
  test/c2h/custom_type.cuh
  test/c2h/generators.cu
  test/catch2_test_block_radix_sort.cu
  test/catch2_test_block_radix_sort.cuh
  test/catch2_test_block_radix_sort_custom.cu
  test/catch2_test_device_radix_sort_custom.cu
  test/catch2_test_helper.h
  test/catch2_test_radix_operations.cu
  test/test_device_radix_sort.cu
Labels: testing: gpuCI passed

#700 Decoupled look-back example
  cub/agent/single_pass_scan_operators.cuh
  examples/device/example_device_decoupled_look_back.cu
  test/catch2_test_device_decoupled_look_back.cu
Labels: testing: gpuCI passed

#706 Fix radix sort / MSVC 2017
  cub/block/radix_rank_sort_operations.cuh
Labels: testing: gpuCI in progress
