Repository NVIDIA/cub, pull requests merged in 2023-03, with the labels that each got.

#630 Cleanup CTK version checks
  cmake/CubHeaderTesting.cmake
  cub/util_type.cuh
  examples/CMakeLists.txt
  test/CMakeLists.txt
  test/test_device_histogram.cu
  test/test_device_radix_sort.cu
  test/test_device_reduce.cu
  test/test_device_segmented_sort.cu
Labels: type: bug: functional, testing: gpuCI in progress

#649 Assert max tile size for radix sort
  cub/block/block_radix_rank.cuh
Labels: testing: gpuCI passed

#616 Port warp tests to use catch2
  test/c2h/generators.cu
  test/catch2_test_helper.h
  test/catch2_test_warp_exchange.cu
  test/catch2_test_warp_mask.cu
  test/catch2_test_warp_scan.cu
  test/catch2_test_warp_store.cu
  test/fill_striped.cuh
  test/test_device_batch_memcpy.cu
  test/test_util.h
  test/test_warp_exchange.cu
  test/test_warp_load.cu
  test/test_warp_mask.cu
  test/test_warp_scan.cu
  test/test_warp_store.cu
Labels: testing: gpuCI passed, area: tests

#632 Fixes overflows for [Multi]HistogramEven over integral types
  cub/device/device_histogram.cuh
  cub/device/dispatch/dispatch_histogram.cuh
  test/test_device_histogram.cu
Labels: testing: gpuCI passed

#652 Fix `cub::DeviceReduce::Arg{Max,Min}` for `inf` values
  .gitignore
  cub/device/device_reduce.cuh
  cub/device/device_segmented_reduce.cuh
  cub/device/dispatch/dispatch_reduce.cuh
  test/test_device_reduce.cu
Labels: testing: gpuCI passed

#657 Fix conversion issues in block histogram test
  test/c2h/generators.cuh
  test/catch2_test_block_histogram.cu
  test/catch2_test_helper.h
Labels: testing: gpuCI passed, only: tests

#658 Deprecate cub::mutex and fix remaining narrowing conversions in tests
  cub/host/mutex.cuh
  cub/util_allocator.cuh
  test/test_device_scan.cu
  test/test_device_scan_by_key.cu
  test/test_device_spmv.cu
Labels: testing: gpuCI passed, release: breaking change

#654 CDP abstraction for CUB tests
  test/CMakeLists.txt
  test/c2h/generators.cu
  test/catch2_test_cdp_helper.h
  test/catch2_test_cdp_wrapper.cu
Labels: testing: gpuCI passed, only: tests, cub

#661 Reduce RAM usage by radix sort tests
  test/test_device_radix_sort.cu
Labels: testing: gpuCI in progress, only: tests

#659 Fix `cub::DeviceSpmv` for empty matrices
  cub/device/dispatch/dispatch_spmv_orig.cuh
Labels: testing: gpuCI in progress

#664 Optimize merge sort
  cub/block/block_merge_sort.cuh
Labels: testing: gpuCI in progress, area: performance

#665 Fix uninitialized copy in block scan raking
  cub/block/specializations/block_scan_raking.cuh
Labels: testing: gpuCI passed
