Repository NVIDIA/cub, pull requests merged in 2023-02, with the labels that each got.

#620 Avoid system thrust usage in tests
  test/CMakeLists.txt
  test/c2h/generators.cu
Labels: type: bug: functional, testing: gpuCI passed, area: tests

#606 Optimize Decoupled Look-Back
  .clangd
  cub/agent/single_pass_scan_operators.cuh
  cub/detail/strong_load.cuh
  cub/detail/strong_store.cuh
Labels: type: bug: functional, testing: gpuCI passed, P0: must have, area: performance

#626 Fixes DeviceMemcpy::Batched for Pre-Volta Architectures
  cub/agent/agent_batch_memcpy.cuh
  cub/util_ptx.cuh
  test/test_device_batch_memcpy.cu
Labels: type: bug: functional, testing: gpuCI in progress, nvbug
