Repository NVIDIA/cub, pull requests merged in 2023-06, with the labels that each got.

#708 Fix CDP test wrapper for CTK 11.5
  test/catch2_test_cdp_helper.h
Labels: testing: gpuCI passed

#712 Introduce SM90 tuning policy into scan
  benchmarks/scripts/analyze.py
  cub/device/dispatch/dispatch_scan.cuh
  cub/thread/thread_operators.cuh
Labels: testing: gpuCI passed

#714 Workaround three-way partition compilation issue
  test/test_device_three_way_partition.cu
Labels: testing: gpuCI passed

#715 Fix reduce by key tile state for Pascal
  cub/agent/single_pass_scan_operators.cuh
Labels: testing: gpuCI passed

#718 Tune select and partition for SM90
  cub/device/dispatch/dispatch_scan.cuh
  cub/device/dispatch/dispatch_select_if.cuh
  cub/device/dispatch/tuning/tuning_scan.cuh
  cub/device/dispatch/tuning/tuning_select_if.cuh
Labels: testing: gpuCI passed

#723 Ensure that any CMake re-rooting doesn't break our find_file.
  cub/cmake/cub-header-search.cmake.in
Labels: monorepo blocker

#721 Tune RLE for SM90
  benchmarks/bench/run_length_encode/encode.cu
  cub/device/device_run_length_encode.cuh
  cub/device/dispatch/dispatch_rle.cuh
  cub/device/dispatch/tuning/tuning_run_length_encode.cuh
Labels: testing: gpuCI passed, monorepo blocker

#722 Improve docs for warp-wide primitives
  cub/warp/warp_exchange.cuh
  cub/warp/warp_load.cuh
  cub/warp/warp_merge_sort.cuh
  cub/warp/warp_reduce.cuh
  cub/warp/warp_scan.cuh
  cub/warp/warp_store.cuh
  docs/index.rst
  docs/repo.toml
Labels: testing: gpuCI passed, monorepo blocker
